version: "3.1"

services:
  mysql:
    image: mysql:9.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-root-pw
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: simpletodo
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
